INSERT INTO "metric_definitions" ("key","name","category","unit","data_type","aggregation")
VALUES
  ('ats.source1.voltage.l1_n','Fuente 1 voltaje L1-N','ats.source1.voltage','V','float','avg'),
  ('ats.source1.voltage.l2_n','Fuente 1 voltaje L2-N','ats.source1.voltage','V','float','avg'),
  ('ats.source1.voltage.l3_n','Fuente 1 voltaje L3-N','ats.source1.voltage','V','float','avg'),
  ('ats.source1.voltage.l1_l2','Fuente 1 voltaje L1-L2','ats.source1.voltage','V','float','avg'),
  ('ats.source1.voltage.l2_l3','Fuente 1 voltaje L2-L3','ats.source1.voltage','V','float','avg'),
  ('ats.source1.voltage.l3_l1','Fuente 1 voltaje L3-L1','ats.source1.voltage','V','float','avg'),
  ('ats.source1.frequency','Fuente 1 frecuencia','ats.source1.frequency','Hz','float','avg'),
  ('ats.source2.voltage.l1_n','Fuente 2 voltaje L1-N','ats.source2.voltage','V','float','avg'),
  ('ats.source2.voltage.l2_n','Fuente 2 voltaje L2-N','ats.source2.voltage','V','float','avg'),
  ('ats.source2.voltage.l3_n','Fuente 2 voltaje L3-N','ats.source2.voltage','V','float','avg'),
  ('ats.source2.voltage.l1_l2','Fuente 2 voltaje L1-L2','ats.source2.voltage','V','float','avg'),
  ('ats.source2.voltage.l2_l3','Fuente 2 voltaje L2-L3','ats.source2.voltage','V','float','avg'),
  ('ats.source2.voltage.l3_l1','Fuente 2 voltaje L3-L1','ats.source2.voltage','V','float','avg'),
  ('ats.source2.frequency','Fuente 2 frecuencia','ats.source2.frequency','Hz','float','avg'),
  ('ats.load.current.l1','Carga corriente L1','ats.load.current','A','float','avg'),
  ('ats.load.current.l2','Carga corriente L2','ats.load.current','A','float','avg'),
  ('ats.load.current.l3','Carga corriente L3','ats.load.current','A','float','avg'),
  ('ats.load.power.active.total','Carga potencia activa total','ats.load.power','kW','float','avg'),
  ('ats.load.power.reactive.total','Carga potencia reactiva total','ats.load.power','kVAr','float','avg'),
  ('ats.load.power.apparent.total','Carga potencia aparente total','ats.load.power','kVA','float','avg'),
  ('ats.load.power_factor','Carga factor de potencia','ats.load.power','','float','avg'),
  ('ats.source1.available','Fuente 1 disponible','ats.status','','boolean','last'),
  ('ats.source2.available','Fuente 2 disponible','ats.status','','boolean','last'),
  ('ats.breaker.source1_closed','Interruptor fuente 1 cerrado','ats.breaker','','boolean','last'),
  ('ats.breaker.source2_closed','Interruptor fuente 2 cerrado','ats.breaker','','boolean','last'),
  ('ats.transfer.position','Posición de transferencia','ats.status','','enum','last'),
  ('ats.common_alarm','Alarma común ATS','ats.alarm','','boolean','last'),
  ('ats.active_alarm_count','Alarmas activas ATS','ats.alarm','','integer','max'),
  ('dse.mode','Modo DSE','dse.status','','enum','last')
ON CONFLICT ("key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "unit" = EXCLUDED."unit",
  "data_type" = EXCLUDED."data_type",
  "aggregation" = EXCLUDED."aggregation",
  "updated_at" = now();