export const HOIT_METRIC_CATALOG = [
  { key: "electrical.voltage.l1_n", name: "Voltaje L1-N", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.voltage.l2_n", name: "Voltaje L2-N", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.voltage.l3_n", name: "Voltaje L3-N", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.voltage.l1_l2", name: "Voltaje L1-L2", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.voltage.l2_l3", name: "Voltaje L2-L3", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.voltage.l3_l1", name: "Voltaje L3-L1", category: "electrical.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "electrical.current.l1", name: "Corriente L1", category: "electrical.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "electrical.current.l2", name: "Corriente L2", category: "electrical.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "electrical.current.l3", name: "Corriente L3", category: "electrical.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "electrical.power.active.total", name: "Potencia activa total", category: "electrical.power", unit: "kW", dataType: "float", aggregation: "avg" },
  { key: "electrical.power.reactive.total", name: "Potencia reactiva total", category: "electrical.power", unit: "kVAr", dataType: "float", aggregation: "avg" },
  { key: "electrical.power.apparent.total", name: "Potencia aparente total", category: "electrical.power", unit: "kVA", dataType: "float", aggregation: "avg" },
  { key: "electrical.power_factor", name: "Factor de potencia", category: "electrical.power", unit: "", dataType: "float", aggregation: "avg" },
  { key: "electrical.frequency", name: "Frecuencia", category: "electrical.frequency", unit: "Hz", dataType: "float", aggregation: "avg" },
  { key: "electrical.energy.import", name: "Energía importada", category: "electrical.energy", unit: "kWh", dataType: "float", aggregation: "counter" },
  { key: "electrical.energy.export", name: "Energía exportada", category: "electrical.energy", unit: "kWh", dataType: "float", aggregation: "counter" },
  { key: "electrical.demand.active", name: "Demanda activa", category: "electrical.demand", unit: "kW", dataType: "float", aggregation: "max" },
  { key: "environment.temperature", name: "Temperatura", category: "environment", unit: "°C", dataType: "float", aggregation: "avg" },
  { key: "sensor.battery_voltage", name: "Voltaje de batería", category: "sensor.health", unit: "V", dataType: "float", aggregation: "last" },
  { key: "sensor.rssi", name: "RSSI", category: "sensor.health", unit: "dBm", dataType: "integer", aggregation: "avg" },
  { key: "sensor.adv_count", name: "Contador de advertising", category: "sensor.health", unit: "", dataType: "integer", aggregation: "counter" },
  { key: "ats.mains.available", name: "Red disponible", category: "ats.status", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.bus.available", name: "Bus disponible", category: "ats.status", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.breaker.mains_closed", name: "Breaker de red cerrado", category: "ats.breaker", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.breaker.bus_closed", name: "Breaker de bus cerrado", category: "ats.breaker", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.source1.voltage.l1_n", name: "Fuente 1 voltaje L1-N", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.voltage.l2_n", name: "Fuente 1 voltaje L2-N", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.voltage.l3_n", name: "Fuente 1 voltaje L3-N", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.voltage.l1_l2", name: "Fuente 1 voltaje L1-L2", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.voltage.l2_l3", name: "Fuente 1 voltaje L2-L3", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.voltage.l3_l1", name: "Fuente 1 voltaje L3-L1", category: "ats.source1.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.frequency", name: "Fuente 1 frecuencia", category: "ats.source1.frequency", unit: "Hz", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l1_n", name: "Fuente 2 voltaje L1-N", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l2_n", name: "Fuente 2 voltaje L2-N", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l3_n", name: "Fuente 2 voltaje L3-N", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l1_l2", name: "Fuente 2 voltaje L1-L2", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l2_l3", name: "Fuente 2 voltaje L2-L3", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.voltage.l3_l1", name: "Fuente 2 voltaje L3-L1", category: "ats.source2.voltage", unit: "V", dataType: "float", aggregation: "avg" },
  { key: "ats.source2.frequency", name: "Fuente 2 frecuencia", category: "ats.source2.frequency", unit: "Hz", dataType: "float", aggregation: "avg" },
  { key: "ats.load.current.l1", name: "Carga corriente L1", category: "ats.load.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "ats.load.current.l2", name: "Carga corriente L2", category: "ats.load.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "ats.load.current.l3", name: "Carga corriente L3", category: "ats.load.current", unit: "A", dataType: "float", aggregation: "avg" },
  { key: "ats.load.power.active.total", name: "Carga potencia activa total", category: "ats.load.power", unit: "kW", dataType: "float", aggregation: "avg" },
  { key: "ats.load.power.reactive.total", name: "Carga potencia reactiva total", category: "ats.load.power", unit: "kVAr", dataType: "float", aggregation: "avg" },
  { key: "ats.load.power.apparent.total", name: "Carga potencia aparente total", category: "ats.load.power", unit: "kVA", dataType: "float", aggregation: "avg" },
  { key: "ats.load.power_factor", name: "Carga factor de potencia", category: "ats.load.power", unit: "", dataType: "float", aggregation: "avg" },
  { key: "ats.source1.available", name: "Fuente 1 disponible", category: "ats.status", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.source2.available", name: "Fuente 2 disponible", category: "ats.status", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.breaker.source1_closed", name: "Interruptor fuente 1 cerrado", category: "ats.breaker", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.breaker.source2_closed", name: "Interruptor fuente 2 cerrado", category: "ats.breaker", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.transfer.position", name: "Posición de transferencia", category: "ats.status", unit: "", dataType: "enum", aggregation: "last" },
  { key: "ats.common_alarm", name: "Alarma común ATS", category: "ats.alarm", unit: "", dataType: "boolean", aggregation: "last" },
  { key: "ats.active_alarm_count", name: "Alarmas activas ATS", category: "ats.alarm", unit: "", dataType: "integer", aggregation: "max" },
  { key: "dse.mode", name: "Modo DSE", category: "dse.status", unit: "", dataType: "enum", aggregation: "last" },
] as const;
